CREATE DATABASE IF NOT EXISTS GRUPOMALLO;
use GRUPOMALLO;

CREATE TABLE `cliente` (
  `IDCLIENTE` int(11) NOT NULL,
  `NOMBRE` varchar(30) DEFAULT NULL,
  `APELLIDO` varchar(30) DEFAULT NULL,
  `DIRECCION` varchar(100) DEFAULT NULL,
  `TELEFONO` decimal(10,0) DEFAULT NULL,
  `FECHA_VISITA` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `contacto` (
  `IDCONTACTO` int(11) NOT NULL,
  `NOMBRE` varchar(50) DEFAULT NULL,
  `APELLIDO` varchar(50) DEFAULT NULL,
  `TELEFONO` varchar(9) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `detalle_factura` (
  `ID_DETALLE` int(11) NOT NULL,
  `IDFACTURA` int(11) DEFAULT NULL,
  `IDPRODUCTO` int(11) DEFAULT NULL,
  `IDMASCOTA` int(11) DEFAULT NULL,
  `FECHA` date DEFAULT NULL,
  `TOTAL` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `empleado` (
  `IDEMPLEADO` int(11) NOT NULL,
  `IDSUCURSAL` int(11) DEFAULT NULL,
  `NOMBRE` varchar(30) DEFAULT NULL,
  `APELLIDO` varchar(30) DEFAULT NULL,
  `CARGO` varchar(15) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `factura` (
  `IDFACTURA` int(11) NOT NULL,
  `IDEMPLEADO` int(11) DEFAULT NULL,
  `IDCLIENTE` int(11) DEFAULT NULL,
  `IDSUCURSAL` int(11) DEFAULT NULL,
  `IDPAGO` int(11) DEFAULT NULL,
  `FECHA` date DEFAULT NULL,
  `TOTAL` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `mascota` (
  `IDMASCOTA` int(11) NOT NULL,
  `IDCLIENTE` int(11) DEFAULT NULL,
  `NOMBRE` varchar(30) DEFAULT NULL,
  `RAZA` varchar(30) DEFAULT NULL,
  `GENERO` varchar(10) DEFAULT NULL,
  `PESO` varchar(20) DEFAULT NULL,
  `VACUNAS` varchar(30) DEFAULT NULL,
  `OBSERVACIONES` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `pago` (
  `IDPAGO` int(11) NOT NULL,
  `IDCLIENTE` int(11) DEFAULT NULL,
  `IDMASCOTA` int(11) DEFAULT NULL,
  `DESCRIPCION` varchar(15) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `producto` (
  `IDPRODUCTO` int(11) NOT NULL,
  `IDPROVEEDOR` int(11) DEFAULT NULL,
  `NOMBRE_PROD` varchar(50) DEFAULT NULL,
  `DESCRIPCION` varchar(200) DEFAULT NULL,
  `CANTIDAD` int(11) DEFAULT NULL,
  `TIPO` varchar(15) DEFAULT NULL,
  `FECHA_RECIBIDO` date DEFAULT NULL,
  `FECHA_EXPIRACION` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `proveedor` (
  `IDPROVEEDOR` int(11) NOT NULL,
  `NOMBRE` varchar(30) DEFAULT NULL,
  `APELLIDO` varchar(30) DEFAULT NULL,
  `DIRECCION` varchar(100) DEFAULT NULL,
  `TELEFONO` varchar(9) DEFAULT NULL,
  `DESCRIPCION` varchar(70) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `sucursal` (
  `IDSUCURSAL` int(11) NOT NULL,
  `NOMBRE` varchar(50) DEFAULT NULL,
  `DIRECCION` varchar(100) DEFAULT NULL,
  `TELEFONO` char(9) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `usuario` (
  `IDUSUARIO` int(11) NOT NULL,
  `NOMBRE` varchar(15) DEFAULT NULL,
  `PASS_USUARIO` varchar(10) DEFAULT NULL,
  `TipoUsuario` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


INSERT INTO `usuario` (`IDUSUARIO`, `NOMBRE`, `PASS_USUARIO`, `TipoUsuario`) VALUES
(1, 'admin', '1234', 1);


ALTER TABLE `cliente`
  ADD PRIMARY KEY (`IDCLIENTE`);


ALTER TABLE `contacto`
  ADD PRIMARY KEY (`IDCONTACTO`);


ALTER TABLE `detalle_factura`
  ADD PRIMARY KEY (`ID_DETALLE`),
  ADD KEY `DETALL_FACT` (`IDFACTURA`);


ALTER TABLE `empleado`
  ADD PRIMARY KEY (`IDEMPLEADO`),
  ADD KEY `EMPLEADO_SUCURSAL` (`IDSUCURSAL`);


ALTER TABLE `factura`
  ADD PRIMARY KEY (`IDFACTURA`),
  ADD KEY `FACTURA_EMPLEAD` (`IDEMPLEADO`),
  ADD KEY `FACTURA_CLIENT` (`IDCLIENTE`),
  ADD KEY `FACTURA_SUCURS` (`IDSUCURSAL`),
  ADD KEY `FACTURA_PAGO` (`IDPAGO`);


ALTER TABLE `mascota`
  ADD PRIMARY KEY (`IDMASCOTA`),
  ADD KEY `MASCOTA_CLIENT` (`IDCLIENTE`);


ALTER TABLE `pago`
  ADD PRIMARY KEY (`IDPAGO`);


ALTER TABLE `producto`
  ADD PRIMARY KEY (`IDPRODUCTO`),
  ADD KEY `PRODUCTO_PROVEE` (`IDPROVEEDOR`);


ALTER TABLE `proveedor`
  ADD PRIMARY KEY (`IDPROVEEDOR`);


ALTER TABLE `sucursal`
  ADD PRIMARY KEY (`IDSUCURSAL`);


ALTER TABLE `usuario`
  ADD PRIMARY KEY (`IDUSUARIO`);


ALTER TABLE `cliente`
  MODIFY `IDCLIENTE` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `contacto`
  MODIFY `IDCONTACTO` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `detalle_factura`
  MODIFY `ID_DETALLE` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `empleado`
  MODIFY `IDEMPLEADO` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `factura`
  MODIFY `IDFACTURA` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `mascota`
  MODIFY `IDMASCOTA` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `pago`
  MODIFY `IDPAGO` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `producto`
  MODIFY `IDPRODUCTO` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `proveedor`
  MODIFY `IDPROVEEDOR` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `sucursal`
  MODIFY `IDSUCURSAL` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `usuario`
  MODIFY `IDUSUARIO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

ALTER TABLE `detalle_factura`
  ADD CONSTRAINT `DETALL_FACT` FOREIGN KEY (`IDFACTURA`) REFERENCES `factura` (`IDFACTURA`);

ALTER TABLE `empleado`
  ADD CONSTRAINT `EMPLEADO_SUCURSAL` FOREIGN KEY (`IDSUCURSAL`) REFERENCES `sucursal` (`IDSUCURSAL`);

ALTER TABLE `factura`
  ADD CONSTRAINT `FACTURA_CLIENT` FOREIGN KEY (`IDCLIENTE`) REFERENCES `cliente` (`IDCLIENTE`),
  ADD CONSTRAINT `FACTURA_EMPLEAD` FOREIGN KEY (`IDEMPLEADO`) REFERENCES `empleado` (`IDEMPLEADO`),
  ADD CONSTRAINT `FACTURA_PAGO` FOREIGN KEY (`IDPAGO`) REFERENCES `pago` (`IDPAGO`),
  ADD CONSTRAINT `FACTURA_SUCURS` FOREIGN KEY (`IDSUCURSAL`) REFERENCES `sucursal` (`IDSUCURSAL`);

ALTER TABLE `mascota`
  ADD CONSTRAINT `MASCOTA_CLIENT` FOREIGN KEY (`IDCLIENTE`) REFERENCES `cliente` (`IDCLIENTE`);

ALTER TABLE `producto`
  ADD CONSTRAINT `PRODUCTO_PROVEE` FOREIGN KEY (`IDPROVEEDOR`) REFERENCES `proveedor` (`IDPROVEEDOR`);
COMMIT;
